### ISSUE TITLE
Keeping the puppet forge module up-to-date

### ISSUE THREAD

**Issue by kreczko** [cernops/puppet-bdii#11]
Dear CERNops devs,

I just stumbled across Puppet 4 incompatibilities with your puppet forge module (CERNOps/bdii).
However, one of them was fixed 5 months ago (0ede6185f63ccf8850d36209c2aeb876a17c364c), the other one yesterday (8bd9486db826118b85733e79f29f28d0d41d3c3f).

Are there any plans to keep the [puppet forge module](https://forge.puppet.com/CERNOps/bdii) up to date (latest is "Version 0.1.0 released Sep 19th 2014")?
The other modules (cvmfs, fetchcrl) seem to be up-to-date.

Cheers,
Luke

**Comment by traylenator** [comment]
@bendylan I'll submit a PR so the auto upload to puppet forge works on Monday

**Comment by samuraiii** [comment]
How does it look with new version?

**Comment by andrea-manzi** [comment]
we finally published the puppet4 compatible version (v 0.2.2) to puppetforge thanks to @traylenator

**Comment by traylenator** [comment]
We should definetly do a major release for dropping  p3 support. I'll do that now.
